sudo: required

language: java

services:
  - docker

install:
  - docker build -t database db/.
  - docker run --rm -d -e MYSQL_ROOT_PASSWORD=semcoursework -p 33060:3306 database
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_install:
  - mvn clean

jobs:
  include:
    - stage: unit tests
      jdk: oraclejdk11
      script: mvn test

    - stage: integration tests
      jdk: oraclejdk11
      script: mvn -Dtest=AppIntegrationTest test

    - stage: GitHub Release
      install: skip
      # We will build the JAR
      jdk: oraclejdk11
      script:
        - echo "Deploying to Github Releases"
        # Package (build) the JAR
        - mvn package -DskipTests=true -Dmaven.javadoc.skip=true
      before_deploy:
        # Set up git user name and tag this commit
        - git config --local user.name "markusmeresma"
        - git config --local user.email "markus.meresma@gmail.com"
        # Create temporary tag from date and Git log.
        - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y-%m-%d')-$(git log --format=%h -1)}
        # Set tog
        - git tag $TRAVIS_TAG
      deploy:
        provider: releases
        # This is the token we set before
        api_key: $GITHUB_OAUTH_TOKEN
        # Copy build JAR file to release. JAR built in $TRAVIS_BUILD_DIR/target
        file: $TRAVIS_BUILD_DIR/target/seCoursework.jar
        skip_cleanup: true

stages:
  - unit tests
  - integration tests
  - name: GitHub Release
    if: branch = master

after_success:
  - docker compose up --abort-on-container-exit
