sudo: required

language: java

services:
  - docker

install:
  - docker build -t database db/.
  - docker run --rm -d -e MYSQL_ROOT_PASSWORD=semcoursework -p 33060:3306 database
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_install:
  - mvn clean

jobs:
  include:
    - stage: unit tests
      jdk: oraclejdk11
      script: mvn -Dtest=WorldQueriesTest, RegionQueriesTest test

    - stage: integration tests
      jdk: oraclejdk11
      script: mvn -Dtest=com.napier.sem.AppIntegrationTest test
    - stage: deploy
      install: skip
      jdk: oraclejdk11
      script: echo "Dummy deploy"

stages:
  - unit tests
  - integration tests
  - name: deploy
    if: branch = master

after_success:
  - docker compose up --abort-on-container-exit
